//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskUpdate.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CustomUserId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string Extenstion { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentId1 { get; set; }
        public string DepartmentName1 { get; set; }
        public Nullable<int> DepartmentId2 { get; set; }
        public string DepartmentName2 { get; set; }
        public string Designation { get; set; }
        public string PlaceAllocation { get; set; }
        public string UserType { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswner { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public string SubDepartmentName { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
        public Nullable<bool> IsEmployeesReporting { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<bool> IsAppLogin { get; set; }
        public Nullable<bool> IsOffRollDoctor { get; set; }
        public Nullable<bool> IsOnRollDoctor { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public string CugNumber { get; set; }
        public string EmployeePhoto { get; set; }
        public string DigitalSignature { get; set; }
    }
}
