//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int LogId { get; set; }
        public string LoginId { get; set; }
        public string LoginType { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public string DayWiseLogDuration { get; set; }
        public string LogStatus { get; set; }
        public string ManualLogOut { get; set; }
        public string Description { get; set; }
        public string MLOStatus { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string SysLogExtra1 { get; set; }
        public string SysLogExtra2 { get; set; }
    }
}
