//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PatientBill
    {
        public int BillId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string DiscountType { get; set; }
        public string ModeOfPayment { get; set; }
        public string CardNumber { get; set; }
        public string NameOfTheCard { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> FinalPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
