//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_att_master
    {
        public int slno { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string empcod { get; set; }
        public string employeeid { get; set; }
        public string cmp_cod { get; set; }
        public string loc_cod { get; set; }
        public string site_cod { get; set; }
        public string shft_type { get; set; }
        public string shft_cod { get; set; }
        public Nullable<System.DateTime> punchdate { get; set; }
        public string in_time { get; set; }
        public string out_time { get; set; }
        public string extrahours { get; set; }
        public string earlyin { get; set; }
        public string earlyout { get; set; }
        public string latein { get; set; }
        public string lateout { get; set; }
        public string holiday { get; set; }
        public string status { get; set; }
        public string auth_latein { get; set; }
        public string auth_earlyout { get; set; }
        public string auth_ot { get; set; }
        public string transact { get; set; }
        public string in_time1 { get; set; }
        public string out_time1 { get; set; }
        public string co_ot { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> lastupdatedon { get; set; }
        public Nullable<decimal> roasterlatein { get; set; }
    }
}
