//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmp_DietMenu
    {
        public int DietMenuId { get; set; }
        public Nullable<int> DietId { get; set; }
        public Nullable<int> MealtypeId { get; set; }
        public Nullable<int> DayNo { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> ItemUnitTypeId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
