//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaskAutoAssignSetting
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public Nullable<int> CreatorDepartmentId { get; set; }
        public Nullable<int> CreatorLocationId { get; set; }
        public string Subject { get; set; }
        public string AssignToUserId { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
