//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoctorPunchInOutEntries
    {
        public int ResponseId { get; set; }
        public string strUserName { get; set; }
        public string strPassword { get; set; }
        public string strInstance { get; set; }
        public string strDate { get; set; }
        public string authenticationStatus { get; set; }
        public string dateFormatStatus { get; set; }
        public string strEmpId { get; set; }
        public string strPunchDate { get; set; }
        public string strPunchTime { get; set; }
        public string strPunchMode { get; set; }
        public string strPunchLatitude { get; set; }
        public string strPunchLongitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
