//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dms
    {
        public int DocumentId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<bool> IsEmpCreated { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> DisplayToEmp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Createdby { get; set; }
    }
}
