//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DrugNicuReport
    {
        public int DrugNICUReportId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public string PatientId { get; set; }
        public string PatientName { get; set; }
        public string StockGivenPerson { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string RoomNo { get; set; }
        public string MrNumber { get; set; }
    }
}
