//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EventManageDelegate
    {
        public int EventDelegateId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public Nullable<System.DateTime> BookingFromDate { get; set; }
        public Nullable<System.DateTime> BookingToDate { get; set; }
        public string Comments { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Workshop { get; set; }
        public Nullable<bool> Conference { get; set; }
        public string UTRTransaction { get; set; }
        public string PaymentType { get; set; }
        public string BankName { get; set; }
        public string CCdetails { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> FinalBlanceTopay { get; set; }
        public Nullable<bool> IsWelcomeKitReceived { get; set; }
    }
}
