//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportingManager
    {
        public int ReportingManagerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsHod { get; set; }
        public Nullable<bool> IsHodOfHod { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public string SubDepartmentName { get; set; }
        public Nullable<bool> Is_OnLeave { get; set; }
        public string Emp_UserId { get; set; }
        public Nullable<bool> IsManagerOfHod { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
