//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EventManagePayment
    {
        public int EventPaymentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public string Remarks { get; set; }
        public string Document1 { get; set; }
        public string Document2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
