//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveUpdateHistory
    {
        public int LeaveUpdateId { get; set; }
        public string UserId { get; set; }
        public string LeaveType { get; set; }
        public Nullable<double> AddedLeaves { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<bool> IsYearly { get; set; }
    }
}
