//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FloorDepartment
    {
        public int Id { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
