//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Drug
    {
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public Nullable<decimal> StockTotal { get; set; }
        public string DrugDescription { get; set; }
        public Nullable<System.DateTime> DrugExpiryDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
