//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ValetParking
    {
        public int ValetParkingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string ParkingAreaName { get; set; }
        public string VehicleNo { get; set; }
        public string InTime { get; set; }
        public string InDriverName { get; set; }
        public string InDriverEmpId { get; set; }
        public string OutTime { get; set; }
        public string OutDriverName { get; set; }
        public string OutDriverEmpId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string MobileNumber { get; set; }
        public string TokenNumber { get; set; }
        public string CheckoutRemarks { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
    }
}
