//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Group
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupLocationId { get; set; }
        public string GroupLocationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
