//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpScheduleBreak
    {
        public int ScheduleBreakId { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
