//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_YearWiseHistory
    {
        public System.Guid ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string LeaveTypeName { get; set; }
        public string CustomUserId { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string JoiningDate_StringFormat { get; set; }
        public Nullable<int> YearCompleted { get; set; }
        public Nullable<System.DateTime> YearCompletedDateTime { get; set; }
        public string YearCompletedDate_StringFormat { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
