//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KraReviewSheetOther
    {
        public int KRASheetOthersID { get; set; }
        public Nullable<int> PerfomanceReview_Id { get; set; }
        public string EmpId { get; set; }
        public string KRACategory { get; set; }
        public string DetailsOfKRA { get; set; }
        public string MeasureOfPerformance { get; set; }
        public string Weightage { get; set; }
        public string DetailsOfAccomplishment { get; set; }
        public string MitigatingReasons { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SelfRatingByAppraisee { get; set; }
        public string AppraiserRating { get; set; }
        public string WeightedRating { get; set; }
    }
}
