//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VehicleRequest
    {
        public int VehicleRequestId { get; set; }
        public string VehicleTypeRequested { get; set; }
        public string VehicleTypeAllocated { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string ArriveTime { get; set; }
        public string StartTime { get; set; }
        public string RequestorComments { get; set; }
        public string Remarks { get; set; }
        public string VehicleDetails { get; set; }
        public string DriverContactDetails { get; set; }
        public string Status { get; set; }
        public string VehicleRegisterType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public string Admin_Status { get; set; }
        public Nullable<long> NoofPersons { get; set; }
        public string returnRequired { get; set; }
        public string Returntime { get; set; }
        public Nullable<System.DateTime> Returndate { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApproverRemarks { get; set; }
        public Nullable<bool> IsRejected { get; set; }
    }
}
