//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AsqQuestions
    {
        public int AsqQuestionId { get; set; }
        public string FillingMonth { get; set; }
        public string FillingPageType { get; set; }
        public Nullable<int> FillingPageTypeOrder { get; set; }
        public string Question { get; set; }
        public string QuestionImage { get; set; }
        public string QuestionOptions { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsNotesRequired { get; set; }
    }
}
