//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaskCpx
    {
        public int TaskCpxId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Item { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Model { get; set; }
        public string MainFeatures { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<bool> Budgeted { get; set; }
        public string Prioriy { get; set; }
        public Nullable<int> RequestForDepartment { get; set; }
        public Nullable<bool> IsNewItem { get; set; }
        public string ItemDetails { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string WorkDoneComments { get; set; }
        public string FinalApprovedAmount { get; set; }
        public string VendorDetails { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string AdminRemarks { get; set; }
        public Nullable<int> CreatorLocationId { get; set; }
        public Nullable<int> CreatorDepartmentId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string ProjectTitle { get; set; }
        public string CpxStatus { get; set; }
        public string CpxRelatedTo { get; set; }
        public Nullable<int> CurrentApprovalLevel { get; set; }
        public string SupportCompany { get; set; }
        public string ReasonForReplacement { get; set; }
        public string OldProductModel { get; set; }
        public Nullable<System.DateTime> AMCLastRenewalDate { get; set; }
        public Nullable<System.DateTime> AMCNextRenewalDate { get; set; }
        public string CPXType { get; set; }
        public string OldProductCost { get; set; }
        public string CpxRelatedToOther { get; set; }
        public string SubProjectTitle { get; set; }
    }
}
