//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bm_Asset
    {
        public int AssetId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public string Equipment { get; set; }
        public string Manufacture { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public string AssetNo { get; set; }
        public string DateOfInstallation { get; set; }
        public Nullable<System.DateTime> PMDone { get; set; }
        public Nullable<System.DateTime> PMDue { get; set; }
        public Nullable<System.DateTime> CALLDone { get; set; }
        public Nullable<System.DateTime> CALLDue { get; set; }
        public string ServiceProviderContact { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ReasonForRemoval { get; set; }
        public string DisposalDocument { get; set; }
        public string AssetStatus { get; set; }
        public Nullable<System.DateTime> CalibrationDue { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string AssetService { get; set; }
        public string PONumber { get; set; }
        public string EquipmentCost { get; set; }
        public string VendorDetails { get; set; }
    }
}
