//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EventManageDelegateMealType
    {
        public int EventDelegateMealTypeId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> MealTypeId { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
