//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubComment
    {
        public int SubCommentId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string Message { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TotalLikes { get; set; }
    }
}
