//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeDetails
    {
        public long EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpDepartmentId { get; set; }
        public string EmpLocationId { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public Nullable<int> EmpAge { get; set; }
        public string Gender { get; set; }
        public string EmpSpouseName { get; set; }
        public string EmpSpouseGender { get; set; }
        public Nullable<System.DateTime> EmpSpouseDOB { get; set; }
        public Nullable<int> EmpSpouseAge { get; set; }
        public string EmpChild1Name { get; set; }
        public string EmpChild1Gender { get; set; }
        public Nullable<System.DateTime> EmpChild1DOB { get; set; }
        public Nullable<int> EmpChild1Age { get; set; }
        public string EmpChild2Name { get; set; }
        public string EmpChild2Gender { get; set; }
        public Nullable<System.DateTime> EmpChild2DOB { get; set; }
        public Nullable<int> EmpChild2Age { get; set; }
        public string EmpRemarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string EmpChild1Relation { get; set; }
        public string EmpChild2Relation { get; set; }
        public string EmpStatus { get; set; }
        public string EmpSpouseRelation { get; set; }
        public string EmpDependantRelation { get; set; }
        public string EmpDependantName { get; set; }
        public string EmpDependantGender { get; set; }
        public Nullable<long> EmpDependantAge { get; set; }
        public Nullable<System.DateTime> EmpDependantDOB { get; set; }
    }
}
