//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmrEntry
    {
        public int EmrEntryId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Mobile { get; set; }
        public string MrNo_PatientName { get; set; }
        public Nullable<System.DateTime> DateofError { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
        public string ReasonForChange { get; set; }
        public string RequestedCorrectionDetails { get; set; }
        public string FormName { get; set; }
        public string Suggestions { get; set; }
        public string ApprovalId1 { get; set; }
        public Nullable<bool> IsApproved1 { get; set; }
        public string Approval1Comments { get; set; }
        public string ApprovalId2 { get; set; }
        public Nullable<bool> IsApproved2 { get; set; }
        public string Approval2Comments { get; set; }
        public string ApprovalId3 { get; set; }
        public Nullable<bool> IsApproved3 { get; set; }
        public string Approval3Comments { get; set; }
        public string ApprovalId4 { get; set; }
        public Nullable<bool> IsApproved4 { get; set; }
        public string Approval4Comments { get; set; }
        public string ApprovalId5 { get; set; }
        public Nullable<bool> IsApproved5 { get; set; }
        public string Approval5Comments { get; set; }
        public string ApprovalId6 { get; set; }
        public Nullable<bool> IsApproved6 { get; set; }
        public string Approval6Comments { get; set; }
        public string ApprovalId7 { get; set; }
        public Nullable<bool> IsApproved7 { get; set; }
        public string Approval7Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifedBy { get; set; }
        public string PatientName { get; set; }
        public string DoctorName { get; set; }
    }
}
