//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cmp_OrderRequestByPatient
    {
        public int PatientDietId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DietId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MealtypeId { get; set; }
        public Nullable<int> OrderRequestId { get; set; }
        public string AssignRoomNo { get; set; }
        public string DeliverRoomNo { get; set; }
        public string AssignBedNo { get; set; }
        public string DeliverBedNo { get; set; }
        public Nullable<int> DeliverDietId { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string ReasonToNotDeliver { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AttendantMeal { get; set; }
    }
}
