//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PerfomanceReview
    {
        public int PerfomanceReview_Id { get; set; }
        public string Employee_Id { get; set; }
        public string Name { get; set; }
        public string Appraiser_Name { get; set; }
        public string Appraiser_Id { get; set; }
        public string Reviewer_Name { get; set; }
        public string Reviewer_Id { get; set; }
        public string Head_Of_Hr { get; set; }
        public string Head_Of_Id { get; set; }
        public string Facilitating_Factors { get; set; }
        public string Inhibiting_Factors { get; set; }
        public string NewSkills_Competencies { get; set; }
        public string Strengths { get; set; }
        public string Improvement { get; set; }
        public string Final_Rating { get; set; }
        public string Comments_Of_The_Appraiser { get; set; }
        public string Comments_Of_The_Reviewer { get; set; }
        public string Comments_Of_The_Appraisee { get; set; }
        public string Year_Of_Rating { get; set; }
        public string Current_Status { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public string SORatng { get; set; }
        public string SODemonstration { get; set; }
        public string WorkOutputRating { get; set; }
        public string WorkOutputDemonstration { get; set; }
        public string ComplianceRating { get; set; }
        public string ComplianceDemonstration { get; set; }
        public string DRRating { get; set; }
        public string DRDemonstration { get; set; }
        public string WLRating { get; set; }
        public string WLDemonstration { get; set; }
        public string JobRating { get; set; }
        public string JobDemonstration { get; set; }
        public string AccomplishmentRating { get; set; }
        public string AccomplishmentDemonstration { get; set; }
        public string TeamOrientationRating { get; set; }
        public string TeamOrientationDemonstration { get; set; }
        public string APRating { get; set; }
        public string APDemonstration { get; set; }
        public string CommunicationRating { get; set; }
        public string CommunicationDemonstration { get; set; }
    }
}
