//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaskRemainderLogs
    {
        public int TaskRemainderLogId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public string SentTo { get; set; }
        public string SentHod { get; set; }
    }
}
