//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_att_master_doctor
    {
        public int Id { get; set; }
        public Nullable<int> employeeid { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string in_time { get; set; }
        public string out_time { get; set; }
        public string extrahours { get; set; }
        public string earlyin { get; set; }
        public string earlyout { get; set; }
        public string latein { get; set; }
        public string lateout { get; set; }
    }
}
