//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AsqForm
    {
        public int AsqId { get; set; }
        public string MotherName { get; set; }
        public string BabyMRNumber { get; set; }
        public Nullable<int> BabyNo { get; set; }
        public string BabyGender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string PersonFilling { get; set; }
        public string RelationshipChild { get; set; }
        public Nullable<int> CommunicationScore { get; set; }
        public Nullable<int> GrossMotorScore { get; set; }
        public Nullable<int> FineMotorScore { get; set; }
        public Nullable<int> ProblemSolvingScore { get; set; }
        public Nullable<int> PersonalSocialScore { get; set; }
        public Nullable<int> OverallScore { get; set; }
        public string FillingMonth { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AdminComments { get; set; }
    }
}
