//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GatePass
    {
        public int GatePassId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string NameOfTheCompany { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Address { get; set; }
        public string AuthorizedByName { get; set; }
        public Nullable<int> AuthorizedByEmpId { get; set; }
        public string AuthorizedByDesignation { get; set; }
        public string AuthorizedByDepartment { get; set; }
        public string ReceivingCompanyName { get; set; }
        public string Comments { get; set; }
        public string GatePassType { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfReturn { get; set; }
        public Nullable<int> ApprovedByEmpId { get; set; }
        public string ApproverComments { get; set; }
        public string ApproverStatus { get; set; }
        public Nullable<int> SecurityAcceptedId { get; set; }
        public string SecurityComments { get; set; }
    }
}
