//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Visitor
    {
        public int VisitorId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string ComingFrom { get; set; }
        public string Purpose { get; set; }
        public string ToMeet { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
