//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hr_RemainderLog
    {
        public int Id { get; set; }
        public Nullable<int> RemainderId { get; set; }
        public Nullable<System.DateTime> SentRemainderOn { get; set; }
        public string RemainderSentTo { get; set; }
        public string RemainderSentCC { get; set; }
        public string RemainderSubject { get; set; }
        public string RemainderBody { get; set; }
    }
}
