//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SettingsResponse
    {
        public int Id { get; set; }
        public Nullable<int> SettingsId { get; set; }
        public string SettingsKey { get; set; }
        public string SettingsValue { get; set; }
        public string Message { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> ResponseParentId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
