//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Event
    {
        public long EventId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string EventType { get; set; }
        public string EventTitle { get; set; }
        public string EventDate { get; set; }
        public string EventTime { get; set; }
        public string EventDuration { get; set; }
        public string EventDescription { get; set; }
        public string EventPriority { get; set; }
        public Nullable<bool> IsPersonalEvent { get; set; }
        public Nullable<int> EventOwnerId { get; set; }
        public string EventOwnerName { get; set; }
        public string EventLocation { get; set; }
        public string EventPageLocation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
