//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_VendorMealRequest
    {
        public int VendorStockRequestId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> TotalQtyRequested { get; set; }
        public Nullable<int> TotalQtyReceived { get; set; }
        public Nullable<int> TotalQtyReturn { get; set; }
        public Nullable<int> TotalQtyDamage { get; set; }
        public string TotalNotes { get; set; }
        public Nullable<int> RequestedEmpId { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<int> ReceiverEmpId { get; set; }
        public Nullable<System.DateTime> ReceivedOnDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
