//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdministrationTrackerPurchase
    {
        public int TrackerPurchaseId { get; set; }
        public Nullable<int> TrackerId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
