//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpCounseling
    {
        public int CounselingId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpComments { get; set; }
        public string CounselingType { get; set; }
        public Nullable<int> DoctorEmpId { get; set; }
        public Nullable<System.DateTime> DateOfSchedule { get; set; }
        public string SlotTime { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Observation { get; set; }
        public Nullable<decimal> CounselingFee { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string OtherColumn { get; set; }
        public string OtherColumn1 { get; set; }
        public string OtherColumn2 { get; set; }
        public string OtherColumn3 { get; set; }
        public string OtherColumn4 { get; set; }
        public string OtherColumn5 { get; set; }
    }
}
