//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_VendorMealRequestMealType
    {
        public int VendorStockRequestMealId { get; set; }
        public Nullable<int> VendorStockRequestId { get; set; }
        public Nullable<int> QtyReceived { get; set; }
        public Nullable<int> QtyReturn { get; set; }
        public Nullable<int> QtyDamage { get; set; }
        public Nullable<int> QtyRequested { get; set; }
        public Nullable<int> MealTypeId { get; set; }
        public string Notes { get; set; }
    }
}
