//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Page
    {
        public int PageId { get; set; }
        public string PageName { get; set; }
        public string PageToRole { get; set; }
        public Nullable<int> PageToGroup { get; set; }
        public string PageContent { get; set; }
        public Nullable<bool> IsPdfView { get; set; }
        public string PdfDocumentLink { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string MenuId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> ForAll { get; set; }
    }
}
