//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VehicleRequestComment
    {
        public int Id { get; set; }
        public Nullable<int> VehicleRequestId { get; set; }
        public string Comment { get; set; }
        public string CommentType { get; set; }
        public Nullable<System.DateTime> CommentOn { get; set; }
        public string CommentBy { get; set; }
    }
}
