//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> CanteenId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public Nullable<int> PaidByEmpId { get; set; }
        public Nullable<int> ReceivedByEmpId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
