//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        public int PatientId { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string ParentName1 { get; set; }
        public string ParentName2 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string MobileNumber { get; set; }
        public string PatientRegisterType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remarks { get; set; }
        public string IPNo { get; set; }
        public string MRNo { get; set; }
        public string Regdt { get; set; }
        public string Regtm { get; set; }
        public string BedNo { get; set; }
        public string RoomType { get; set; }
        public string BedId { get; set; }
        public string RoomId { get; set; }
        public string RoomNo { get; set; }
        public string LocationId { get; set; }
        public string LocationName { get; set; }
        public string FloorNo { get; set; }
        public string FloorId { get; set; }
        public Nullable<bool> Bedallocated { get; set; }
    }
}
