//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TravelDesk
    {
        public int TravelDeskId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpName { get; set; }
        public string MailId { get; set; }
        public string Designation { get; set; }
        public string TravelCategory { get; set; }
        public string TravelSubCategory { get; set; }
        public string NameOfConference { get; set; }
        public string EmployeeCategory { get; set; }
        public Nullable<System.DateTime> DateOfJourney { get; set; }
        public string PlaceFrom { get; set; }
        public string PlaceTo { get; set; }
        public Nullable<System.DateTime> DateOfReturnJourney { get; set; }
        public string ReturnPlaceFrom { get; set; }
        public string ReturnPlaceTo { get; set; }
        public Nullable<bool> Accommodation { get; set; }
        public string SpecialNote { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> TotalCostOfTravel { get; set; }
        public Nullable<bool> InBudget { get; set; }
        public string CurrentState { get; set; }
        public Nullable<int> CurrentUser { get; set; }
    }
}
