//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailyVisiting
    {
        public int DailyVisitingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string DepartmentName { get; set; }
        public string PatientType { get; set; }
        public string PatientName { get; set; }
        public string MobileNo { get; set; }
        public string MrNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string TokenNumber { get; set; }
        public string TokenNo { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string VisitingType { get; set; }
        public string ComingFrom { get; set; }
        public string WhomToMeet { get; set; }
        public string Purpose { get; set; }
        public string InTime { get; set; }
        public string InSign { get; set; }
        public string OutTime { get; set; }
        public string OutSign { get; set; }
        public string SecuritySignature { get; set; }
    }
}
