//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdministrationTracker
    {
        public int TrackerId { get; set; }
        public string Title { get; set; }
        public string FormType { get; set; }
        public string LocationId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> NextRenewalDate { get; set; }
        public Nullable<int> Remainder1NoOfDays { get; set; }
        public string Remainder1NoOfDaysNotes { get; set; }
        public Nullable<int> Remainder2NoOfDays { get; set; }
        public string Remainder2NoOfDaysNotes { get; set; }
        public Nullable<int> Remainder3NoOfDays { get; set; }
        public string Remainder3NoOfDaysNotes { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DepartmentId { get; set; }
        public string PrimaryUserId { get; set; }
        public string SecondaryUserid { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string LicenseDepartmentName_Gov { get; set; }
        public string AgreementSubType { get; set; }
    }
}
