//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public int DepartmentId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> ShowInHelpDesk { get; set; }
        public Nullable<bool> ShowInCallCenter { get; set; }
    }
}
