//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NursingDetails
    {
        public int NursingDetailsId { get; set; }
        public string NameOfStudent { get; set; }
        public string FatherName { get; set; }
        public string DateOfBirth { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Qualification { get; set; }
        public string HallTicketNo { get; set; }
        public string FinalRatingComments { get; set; }
        public string DateOfJoining { get; set; }
        public string DateOfRelieving { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Course { get; set; }
        public string Religion { get; set; }
        public string IndentificationMarks { get; set; }
        public string AdmissionNo { get; set; }
        public string RegistrationNo { get; set; }
        public string ResultsParticulars_PTS { get; set; }
        public string ResultsParticulars_PTS_date { get; set; }
        public string ResultsParticulars_PTS_remarks { get; set; }
        public string ResultsParticulars_1styear { get; set; }
        public string ResultsParticulars_1styear_date { get; set; }
        public string ResultsParticulars_1styear_remarks { get; set; }
        public string ResultsParticulars_2ndyear { get; set; }
        public string ResultsParticulars_2ndyear_date { get; set; }
        public string ResultsParticulars_2ndyear_remarks { get; set; }
        public string ResultsParticulars_3rdyear { get; set; }
        public string ResultsParticulars_3rdyear_date { get; set; }
        public string ResultsParticulars_3rdyear_remarks { get; set; }
        public string ResultsParticulars_Internship { get; set; }
        public string ResultsParticulars_Internship_date { get; set; }
        public string ResultsParticulars_Internship_remarks { get; set; }
    }
}
