//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_Store
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreCode { get; set; }
        public string StoreAddress { get; set; }
        public Nullable<int> StoreInchargeEmpId { get; set; }
        public Nullable<int> StoreInchargeSecondaryEmpId { get; set; }
        public Nullable<int> StoreManagerEmpId { get; set; }
        public Nullable<int> StoreAsstManagerEmpId { get; set; }
        public string StoreDescription { get; set; }
        public Nullable<int> StoreLocation { get; set; }
        public Nullable<bool> Iskitchen { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string TypeOf { get; set; }
    }
}
