//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminCategory
    {
        public int CategoryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FormType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string UserHelpdocument { get; set; }
    }
}
