//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AsqSubForm
    {
        public int Id { get; set; }
        public Nullable<int> AsqId { get; set; }
        public string FillingType { get; set; }
        public string Answner1 { get; set; }
        public string Answner2 { get; set; }
        public string Answner3 { get; set; }
        public string Answner4 { get; set; }
        public string Answner5 { get; set; }
        public string Answner6 { get; set; }
        public string Answner7 { get; set; }
        public string Answner8 { get; set; }
        public string Answner9 { get; set; }
        public string Answner10 { get; set; }
        public string Answner11 { get; set; }
        public string Answner12 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> QuestionId1 { get; set; }
        public Nullable<int> QuestionId2 { get; set; }
        public Nullable<int> QuestionId3 { get; set; }
        public Nullable<int> QuestionId4 { get; set; }
        public Nullable<int> QuestionId5 { get; set; }
        public Nullable<int> QuestionId6 { get; set; }
        public Nullable<int> QuestionId7 { get; set; }
        public Nullable<int> QuestionId8 { get; set; }
        public Nullable<int> QuestionId9 { get; set; }
        public Nullable<int> QuestionId10 { get; set; }
        public Nullable<int> QuestionId11 { get; set; }
        public Nullable<int> QuestionId12 { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public string Remarks4 { get; set; }
        public string Remarks5 { get; set; }
        public string Remarks6 { get; set; }
        public string Remarks7 { get; set; }
        public string Remarks8 { get; set; }
        public string Remarks9 { get; set; }
        public string Remarks10 { get; set; }
        public string Remarks11 { get; set; }
        public string Remarks12 { get; set; }
    }
}
