//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hr_Remainder
    {
        public int RemainderId { get; set; }
        public string Title { get; set; }
        public Nullable<int> RemainderTypeId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string NursingCouncil { get; set; }
        public string FirstRegistrationCouncil { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> LastRenewalDate { get; set; }
        public Nullable<System.DateTime> NextRenewalDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsCommon { get; set; }
    }
}
