//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NotificationLog
    {
        public int Id { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string Message { get; set; }
        public string ClickAction { get; set; }
        public string Params { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string SentResponse { get; set; }
    }
}
