//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Location
    {
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public string companyid { get; set; }
        public string locid { get; set; }
        public Nullable<bool> ShowinCPX { get; set; }
        public Nullable<bool> ShowasSubLocation { get; set; }
        public Nullable<int> ParentLocationId { get; set; }
    }
}
