//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaskApprove
    {
        public int TaskApproveId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ApproveEmpId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApproveComments { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovalLevel { get; set; }
    }
}
