//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AcademicsVideoHistory
    {
        public int HistoryId { get; set; }
        public Nullable<int> AcademicsVideoId { get; set; }
        public string UserId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TotalNoOfViews { get; set; }
        public Nullable<System.DateTime> DateOfViwed { get; set; }
        public Nullable<System.DateTime> DateOfLastViwed { get; set; }
    }
}
