//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Place
    {
        public int PlaceId { get; set; }
        public string PlaceNo { get; set; }
        public string PlaceExtension { get; set; }
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public string RoomExtension { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string FloorName { get; set; }
        public int BuildingId { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
