//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssetComponent
    {
        public int AssetComponentId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public Nullable<int> AssetTypeComponentId { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Warranty { get; set; }
        public string Remarks { get; set; }
        public string Impact { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
