//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Asset_MobileAllotment
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SerialNumber { get; set; }
        public string BatterySerialNo { get; set; }
        public Nullable<System.DateTime> DOP { get; set; }
        public string IMEINO { get; set; }
        public string AssetLabel { get; set; }
        public string Accessories { get; set; }
        public string MonthlyPlan { get; set; }
        public string SIMNO { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> AssigntoEmpId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string AssignComments { get; set; }
        public Nullable<int> IssuedByEmpId { get; set; }
        public string AssignEmpAchknowledged { get; set; }
        public string AssetStatus { get; set; }
        public Nullable<int> ReturnReceivedBy { get; set; }
        public Nullable<System.DateTime> ReturnReceivedOn { get; set; }
        public string ReturnReceivedComments { get; set; }
        public Nullable<bool> CanReUse { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CellPhoneRequestId { get; set; }
        public string IMEINO2 { get; set; }
    }
}
