//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAssets
    {
        public int UserAssetId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<System.DateTime> DateOfAssign { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AllocationRequestId { get; set; }
        public string AllocationStatus { get; set; }
        public string AssetSerialNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> DeAllocationRequestId { get; set; }
        public Nullable<System.DateTime> DeAllocateDate { get; set; }
        public string DeAllocateComments { get; set; }
        public string DeAllocateStatus { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string AssetAllocationType { get; set; }
    }
}
