//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppraiseeDevelopmentTraning
    {
        public int Development_TrainingId { get; set; }
        public Nullable<int> PerfomanceReview_Id { get; set; }
        public string Area_Of_Improvement { get; set; }
        public string Actions_The_Appraisee { get; set; }
        public string Additional_Developmental { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_by { get; set; }
    }
}
