//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpSchedule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> DateOfSchedule { get; set; }
        public Nullable<int> SlotDuration { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<bool> IsDayBlocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
