//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpCounselingFamily
    {
        public int Id { get; set; }
        public Nullable<int> CounselingId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public string Age { get; set; }
        public string Relation { get; set; }
        public string Observation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string OtherColumn { get; set; }
        public string OtherColumn1 { get; set; }
        public string OtherColumn2 { get; set; }
        public string OtherColumn3 { get; set; }
    }
}
