//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaskSLAUser
    {
        public int TaskSLAUserId { get; set; }
        public Nullable<int> TaskLocationId { get; set; }
        public Nullable<int> TaskDepartmentId { get; set; }
        public string EmpEmail { get; set; }
        public string EmpMobile { get; set; }
        public Nullable<int> SLAUserId { get; set; }
        public string TypeOfRequest { get; set; }
        public Nullable<int> TaskLevel { get; set; }
        public string Description { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
