//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TravelDeskDocument
    {
        public int TravelDeskDocumentId { get; set; }
        public Nullable<int> TravelDeskId { get; set; }
        public string Name { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
    }
}
