//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Share
    {
        public int ShareId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string SharedBy { get; set; }
        public Nullable<System.DateTime> SharedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
