//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doula
    {
        public int DoulaId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string MrNumber { get; set; }
        public string PatientName { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string IpNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SpecificDoula { get; set; }
        public string PaymentStatus { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
    }
}
