//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TravelDeskReimbursementform
    {
        public int ReimbursementId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string ConferenceName { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> ConferenceDate { get; set; }
        public Nullable<bool> IsTravelExpense { get; set; }
        public Nullable<decimal> TravelExpense { get; set; }
        public Nullable<bool> IsAccommodation { get; set; }
        public Nullable<decimal> Accommodation { get; set; }
        public Nullable<bool> IsMiscellaneous { get; set; }
        public Nullable<decimal> MiscellaneousAmount { get; set; }
        public Nullable<bool> IsRegistrationFee { get; set; }
        public Nullable<decimal> RegistrationFeeAmount { get; set; }
        public Nullable<int> TravelRequestId { get; set; }
        public Nullable<int> HodUserId { get; set; }
        public string HodAction { get; set; }
        public string HodRemarks { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public string AccountDeptAction { get; set; }
        public string AccountDeptRemarks { get; set; }
        public Nullable<int> AccountDeptUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string PaidThrough { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Notes { get; set; }
        public string TravellerDetails { get; set; }
    }
}
