//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Concession
    {
        public int ConcessionId { get; set; }
        public Nullable<System.DateTime> DateOfSubmit { get; set; }
        public string IPNumber { get; set; }
        public string PatientName { get; set; }
        public string Category { get; set; }
        public string ConcessionAdvised { get; set; }
        public string Justification { get; set; }
        public string TotalBillAmount { get; set; }
        public string TotalConcessionAmount { get; set; }
        public string ConcessionType { get; set; }
        public string Package { get; set; }
        public string PaidByPatient { get; set; }
        public string Service { get; set; }
        public string Consultation { get; set; }
        public string Scan { get; set; }
        public string Investigations { get; set; }
        public string ProcedureName { get; set; }
        public string Status { get; set; }
        public string ApproverStatus { get; set; }
        public string ApproverComments { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string SubCategory { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public string TotalConcessionPercentage { get; set; }
        public Nullable<int> ConsultantId { get; set; }
        public string ConsultantApproveStatus { get; set; }
        public string ConsultantComments { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string Document { get; set; }
        public string Pharmacy { get; set; }
        public string NST { get; set; }
        public string DateOfAdmission { get; set; }
        public string DateOfDischarge { get; set; }
    }
}
