//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Task
    {
        public long TaskId { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public Nullable<System.DateTime> CallStartDateTime { get; set; }
        public Nullable<int> CreatorLocationId { get; set; }
        public string CreatorLocationName { get; set; }
        public Nullable<int> CreatorDepartmentId { get; set; }
        public string CreatorDepartmentName { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string CreatorName { get; set; }
        public string CreatorPlace { get; set; }
        public string AssertEquipId { get; set; }
        public string AssertEquipName { get; set; }
        public string CategoryOfComplaint { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssignLocationId { get; set; }
        public string AssignLocationName { get; set; }
        public Nullable<int> AssignDepartmentId { get; set; }
        public string AssignDepartmentName { get; set; }
        public Nullable<int> AssignId { get; set; }
        public string AssignName { get; set; }
        public string WorkDoneRemarks { get; set; }
        public Nullable<System.DateTime> CallEndDateTime { get; set; }
        public string AssignStatus { get; set; }
        public string CreatorStatus { get; set; }
        public string LatestComment { get; set; }
        public string TaskDoneByUserId { get; set; }
        public string TaskDoneByName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ExtensionNo { get; set; }
        public string EmailId { get; set; }
        public string Others { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsVendorTicket { get; set; }
        public Nullable<System.DateTime> CapexPrepareDate { get; set; }
        public Nullable<System.DateTime> CapexApproveDate { get; set; }
        public string TaskType { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> DocumentReceived { get; set; }
    }
}
