//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_ItemTransfer
    {
        public int ItemTransferId { get; set; }
        public Nullable<int> FromStoreId { get; set; }
        public Nullable<int> ToStoreId { get; set; }
        public string ModeOfTransfer { get; set; }
        public Nullable<int> SenderEmpId { get; set; }
        public Nullable<int> ReceiverEmpId { get; set; }
        public string SenderAttachment { get; set; }
        public string ReceiverAttachment { get; set; }
        public string SenderNotes { get; set; }
        public string ReceiverNotes { get; set; }
        public string SentOnDate { get; set; }
        public string SentOnTime { get; set; }
        public string ReceivedOnDate { get; set; }
        public string ReceivedOnTime { get; set; }
        public Nullable<int> RequestedEmpId { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public string RequestorNotes { get; set; }
        public Nullable<bool> IsCanteen { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
