//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TravelDeskReimbursementDocument
    {
        public int Id { get; set; }
        public Nullable<int> ReimbursementId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentUrl { get; set; }
        public string ReimbursementType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
