//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bm_AssetTransfer
    {
        public int AssetTransferId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> FromLocationId { get; set; }
        public Nullable<int> FromDepartmentId { get; set; }
        public Nullable<int> FromSubDepartmentId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> ToDepartmentId { get; set; }
        public Nullable<int> ToSubDepartmentId { get; set; }
        public string Document { get; set; }
        public string ReasonForTranfer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
