//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Holiday
    {
        public int HolidayId { get; set; }
        public string HolidayTitle { get; set; }
        public string HolidayDescription { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> HolidayYear { get; set; }
        public string HolidayType { get; set; }
        public Nullable<bool> IsHolidayAddedInDutyRoster { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
