//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobsHistory
    {
        public int Id { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> JobExecutedDate { get; set; }
        public Nullable<int> JobExcutedHour { get; set; }
        public Nullable<int> JobExcutedMinute { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public string Message { get; set; }
        public string Environment { get; set; }
    }
}
