//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssetTranfer
    {
        public int RequestId { get; set; }
        public Nullable<int> UserAssetId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> RequestUserId { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public Nullable<int> CurrentLocationId { get; set; }
        public Nullable<int> CurrentDepartmentId { get; set; }
        public Nullable<int> CurrentUserId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> ToDepartmentId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string ReasonToTranfer { get; set; }
        public string Remarks { get; set; }
        public string TranferStatus { get; set; }
        public Nullable<bool> IsHODApproved { get; set; }
        public string HODComments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> FromBuildingId { get; set; }
        public Nullable<int> FromFloorId { get; set; }
        public Nullable<int> FromRoomId { get; set; }
        public Nullable<int> ToBuildingId { get; set; }
        public Nullable<int> ToFloorId { get; set; }
        public Nullable<int> ToRoomId { get; set; }
    }
}
