//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usernotes
    {
        public int Commentid { get; set; }
        public Nullable<long> Userid { get; set; }
        public string UserCustomId { get; set; }
        public string Comments { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public string Commentshead { get; set; }
    }
}
