//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hr_RemainderType
    {
        public int RemainderTypeId { get; set; }
        public string RemainderType { get; set; }
        public Nullable<bool> RemainderSentToEmployee { get; set; }
        public Nullable<bool> RemainderSentToHOD { get; set; }
        public string RemainderSentToEmail { get; set; }
        public Nullable<int> RemainderNoOfDays { get; set; }
        public string RemainderNoOfDaysNotes { get; set; }
        public string RemainderRepeatType { get; set; }
        public string RemainderSentType { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RemainderNoOfDays1 { get; set; }
        public Nullable<int> RemainderNoOfDays2 { get; set; }
        public Nullable<int> RemainderNoOfDays3 { get; set; }
        public Nullable<int> RemainderNoOfDays4 { get; set; }
        public Nullable<bool> RemainderSentToEmployee1 { get; set; }
        public Nullable<bool> RemainderSentToHOD1 { get; set; }
        public Nullable<bool> RemainderSentToEmployee2 { get; set; }
        public Nullable<bool> RemainderSentToHOD2 { get; set; }
        public Nullable<bool> RemainderSentToEmployee3 { get; set; }
        public Nullable<bool> RemainderSentToHOD3 { get; set; }
        public Nullable<bool> RemainderSentToEmployee4 { get; set; }
        public Nullable<bool> RemainderSentToHOD4 { get; set; }
    }
}
