//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_Canteen
    {
        public int CanteenId { get; set; }
        public string CanteenName { get; set; }
        public string CanteenCode { get; set; }
        public string CanteenDescription { get; set; }
        public Nullable<int> CanteenLocation { get; set; }
        public string CanteenAddress { get; set; }
        public Nullable<int> CanteenInchargeEmpId { get; set; }
        public Nullable<int> CanteenInchargeSecondaryEmpId { get; set; }
        public Nullable<int> CanteenManagerEmpId { get; set; }
        public Nullable<int> CanteenAsstManagerEmpId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
