//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompOffEncash
    {
        public int CompOffEncashId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<System.DateTime> SubmitedOn { get; set; }
        public string ReportingTo { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> HRApproved { get; set; }
        public string Remarks { get; set; }
        public string HrRemarks { get; set; }
        public Nullable<System.DateTime> HrEnchashedDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
