//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RefundRequestComment
    {
        public int RefundRequestCommentId { get; set; }
        public Nullable<int> RefundRequestId { get; set; }
        public string Comment { get; set; }
        public string CommentedBy { get; set; }
        public string CommentedType { get; set; }
        public Nullable<System.DateTime> CommentedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
