//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GatePassComment
    {
        public int Id { get; set; }
        public Nullable<int> GatePassId { get; set; }
        public string CurrentWorkFlow { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedOn { get; set; }
    }
}
