//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_MealType
    {
        public int MealTypeId { get; set; }
        public string MealTypeName { get; set; }
        public string MealTypeCode { get; set; }
        public string MealTypeDescription { get; set; }
        public int SequenceNo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string MealTime { get; set; }
        public Nullable<int> OpenForOrderFromHour { get; set; }
        public Nullable<int> OpenForOrderToHour { get; set; }
    }
}
