//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RefundRequest
    {
        public int RefundRequestId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Justification { get; set; }
        public string ModeUsed { get; set; }
        public string ModeUsedDetails { get; set; }
        public string PatientName { get; set; }
        public string PatientIpNo { get; set; }
        public string PatientMrNo { get; set; }
        public string PatientMobile { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string RefundBillNo { get; set; }
        public string AccountHolderName { get; set; }
        public string IFSC { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string Branch { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CreatorLocationId { get; set; }
        public Nullable<int> CreatorDepartmentId { get; set; }
        public string PatientEmail { get; set; }
        public string Column1 { get; set; }
        public Nullable<int> LastAcceptedBy { get; set; }
        public Nullable<System.DateTime> LastAcceptedOn { get; set; }
        public Nullable<int> LastApprovedRejectedBy { get; set; }
        public Nullable<System.DateTime> LastApprovedRejectedOn { get; set; }
    }
}
