//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssetHistory
    {
        public int AssetHistoryId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string LogSubject { get; set; }
        public string LogDescription { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
