//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Leave
    {
        public long LeaveId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public string LeaveTypeName { get; set; }
        public Nullable<bool> IsFullday { get; set; }
        public Nullable<bool> IsCompOff { get; set; }
        public Nullable<System.DateTime> DateofAvailableCompoff { get; set; }
        public Nullable<System.DateTime> LeaveFromDate { get; set; }
        public Nullable<System.DateTime> LeaveTodate { get; set; }
        public string ReasonForLeave { get; set; }
        public string AddressOnLeave { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Level1Approver { get; set; }
        public Nullable<bool> Level1Approved { get; set; }
        public string Level1ApproveComment { get; set; }
        public string Level2Approver { get; set; }
        public Nullable<bool> Level2Approved { get; set; }
        public string Level2ApproveComment { get; set; }
        public string Level3Approver { get; set; }
        public Nullable<bool> Level3Approved { get; set; }
        public string Level3ApproveComment { get; set; }
        public string LeaveStatus { get; set; }
        public string LeaveSessionDay { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<double> LeaveCount { get; set; }
        public Nullable<System.DateTime> DateOfCompOffLeave { get; set; }
        public string WeeklyOffDay { get; set; }
    }
}
