//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bm_CheckListItem
    {
        public int Id { get; set; }
        public Nullable<int> PreventiveCheckListId { get; set; }
        public string SubName { get; set; }
        public string CheckListType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
