//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Oracle_subdepts
    {
        public int id { get; set; }
        public string sdeptid { get; set; }
        public string deptid { get; set; }
        public string subdeptnm { get; set; }
    }
}
