//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CellPhoneRequest
    {
        public int CellPhoneRequestId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public string Department { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> IsHODApproved { get; set; }
        public string HODComments { get; set; }
        public Nullable<bool> IsAdministratorApproved { get; set; }
        public string AdministratorComments { get; set; }
        public string CurrentApprover { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string RequestType { get; set; }
        public string ApprovedRequestType { get; set; }
        public string NewOrRepair { get; set; }
        public Nullable<System.DateTime> HODApprovedOn { get; set; }
        public Nullable<System.DateTime> AdminApprovedOn { get; set; }
        public Nullable<int> ITUpdatedBy { get; set; }
        public Nullable<int> ITUpdatedOn { get; set; }
    }
}
