//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_ReceivedStockItem
    {
        public int Id { get; set; }
        public Nullable<int> ReceivedStockId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> QtyRequested { get; set; }
        public Nullable<decimal> QtySend { get; set; }
        public Nullable<decimal> QtyRecived { get; set; }
        public Nullable<decimal> QtyReturn { get; set; }
        public Nullable<decimal> QtyDamage { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
