//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notification
    {
        public long NotificationId { get; set; }
        public string Notification { get; set; }
        public string NotificationFrom { get; set; }
        public string NotificationTo { get; set; }
        public Nullable<int> ToDeptId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public string FromComment { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string ToComment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
