//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cm_Transaction
    {
        public int TransactionId { get; set; }
        public string TransactionCustomerType { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string DiscountType { get; set; }
        public string ModeOfPayment { get; set; }
        public string CardNumber { get; set; }
        public string NameOfTheCard { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> FinalPrice { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public string EmpName { get; set; }
        public string EmpMobile { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<bool> IsFreeMeal { get; set; }
        public Nullable<int> CanteenId { get; set; }
        public Nullable<int> SalesEmpId { get; set; }
        public string SalesEmpNotes { get; set; }
        public string BillAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> TotalPaidAmount { get; set; }
        public string SaleType { get; set; }
        public string PatientId { get; set; }
        public string InPatientdRoomNo { get; set; }
    }
}
