//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSchedule.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTable
    {
        public string cmp_cod { get; set; }
        public string Loc_Cod { get; set; }
        public Nullable<System.DateTime> Pch_Date { get; set; }
        public string Site_Code { get; set; }
        public string Card_ID { get; set; }
        public string Tot_Min { get; set; }
        public string Pch_Time { get; set; }
        public string Pch_Status { get; set; }
        public string Pch_KeyCode { get; set; }
        public string myflag { get; set; }
        public byte[] emppic { get; set; }
        public string emppath { get; set; }
        public string myrtype { get; set; }
        public string pch_time1 { get; set; }
        public string outreason { get; set; }
        public string outremark { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> recorddatetime { get; set; }
        public string indexno { get; set; }
        public long ID { get; set; }
    }
}
