//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSchedule.CurrentDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyIntranetAppEntities : DbContext
    {
        public MyIntranetAppEntities()
            : base("name=MyIntranetAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_att_master> tbl_att_master { get; set; }
        public virtual DbSet<tbl_att_master_doctor> tbl_att_master_doctor { get; set; }
        public virtual DbSet<tbl_Leave> tbl_Leave { get; set; }
        public virtual DbSet<tbl_LeaveType> tbl_LeaveType { get; set; }
        public virtual DbSet<tbl_Permission> tbl_Permission { get; set; }
        public virtual DbSet<tbl_Roaster> tbl_Roaster { get; set; }
        public virtual DbSet<tbl_ShiftType> tbl_ShiftType { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
