//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSchedule.CurrentDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveType
    {
        public int LeaveTypeId { get; set; }
        public string LeaveName { get; set; }
        public Nullable<int> MaxLeavePerMonth { get; set; }
        public Nullable<int> MinLeavePerMonth { get; set; }
        public Nullable<int> NoOfTimesPerYear { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
