//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSchedule.CurrentDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Permission
    {
        public long PermissionId { get; set; }
        public Nullable<System.DateTime> PermissionDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Reason { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> Level1Approved { get; set; }
        public string Level1ApproveComment { get; set; }
        public Nullable<bool> Level2Approved { get; set; }
        public string Level2ApproveComment { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Level1Approver { get; set; }
        public string Level2Approver { get; set; }
        public string Status { get; set; }
    }
}
