//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyIntranetApp_RegisterEntities : DbContext
    {
        public MyIntranetApp_RegisterEntities()
            : base("name=MyIntranetApp_RegisterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Register_Fuel> tbl_Register_Fuel { get; set; }
        public virtual DbSet<tbl_Register_Key> tbl_Register_Key { get; set; }
        public virtual DbSet<tbl_Register_LifeCell> tbl_Register_LifeCell { get; set; }
        public virtual DbSet<tbl_Register_PatientTransfer> tbl_Register_PatientTransfer { get; set; }
        public virtual DbSet<tbl_Register_Daak> tbl_Register_Daak { get; set; }
        public virtual DbSet<tbl_Register_Demo> tbl_Register_Demo { get; set; }
        public virtual DbSet<tbl_Register_LostFound> tbl_Register_LostFound { get; set; }
        public virtual DbSet<tbl_Register_PatientDischarge> tbl_Register_PatientDischarge { get; set; }
        public virtual DbSet<tbl_Register_BioMedicalWaste> tbl_Register_BioMedicalWaste { get; set; }
        public virtual DbSet<tbl_Register_InternalInward> tbl_Register_InternalInward { get; set; }
        public virtual DbSet<tbl_Register_InwardNonReturnable> tbl_Register_InwardNonReturnable { get; set; }
        public virtual DbSet<tbl_Register_InWardReturnable> tbl_Register_InWardReturnable { get; set; }
        public virtual DbSet<tbl_Register_OutWardNonReturnable> tbl_Register_OutWardNonReturnable { get; set; }
        public virtual DbSet<tbl_Register_OutWardReturnable> tbl_Register_OutWardReturnable { get; set; }
        public virtual DbSet<tbl_Register_VehicleMovement> tbl_Register_VehicleMovement { get; set; }
        public virtual DbSet<tbl_Register_VehicleParking> tbl_Register_VehicleParking { get; set; }
        public virtual DbSet<tbl_ParkingLocation> tbl_ParkingLocation { get; set; }
        public virtual DbSet<tbl_Patient_Movement_Register> tbl_Patient_Movement_Register { get; set; }
        public virtual DbSet<tbl_Lms_CourceTrainee> tbl_Lms_CourceTrainee { get; set; }
        public virtual DbSet<tbl_Lms_Course> tbl_Lms_Course { get; set; }
        public virtual DbSet<tbl_Lms_CoursePage> tbl_Lms_CoursePage { get; set; }
        public virtual DbSet<tbl_Lms_CourseQuiz> tbl_Lms_CourseQuiz { get; set; }
        public virtual DbSet<tbl_Lms_CourseTrainer> tbl_Lms_CourseTrainer { get; set; }
        public virtual DbSet<tbl_LMS_TraineeQuiz> tbl_LMS_TraineeQuiz { get; set; }
        public virtual DbSet<tbl_Register_Occurance> tbl_Register_Occurance { get; set; }
        public virtual DbSet<tbl_Register_Posting> tbl_Register_Posting { get; set; }
        public virtual DbSet<tbl_Register_MobileDepositing> tbl_Register_MobileDepositing { get; set; }
        public virtual DbSet<tbl_Register_NursingOuting> tbl_Register_NursingOuting { get; set; }
        public virtual DbSet<tbl_Register_Round> tbl_Register_Round { get; set; }
    }
}
