//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient_Movement_Register
    {
        public int Id { get; set; }
        public string PatientMRNo { get; set; }
        public string NameOfPatient { get; set; }
        public string Mobile { get; set; }
        public string Ward { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string RoomNo { get; set; }
        public string ConsultantName { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> DateOfRegister { get; set; }
        public string OutPerson { get; set; }
        public string OutPersonSign { get; set; }
        public string InPerson { get; set; }
        public string InPersonSign { get; set; }
        public string InSecurity { get; set; }
        public string InSecuritySign { get; set; }
        public string OutSecurity { get; set; }
        public string OutSecuritySign { get; set; }
        public string InWard { get; set; }
    }
}
