//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_NursingOuting
    {
        public int Id { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string Deparment { get; set; }
        public string EmployeeLocation { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string ReasonForGoing { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutSecurity { get; set; }
        public string OutSecuritySign { get; set; }
        public string OutEmployeeSign { get; set; }
        public string OutRemarks { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string InSecurity { get; set; }
        public string InSecuritySign { get; set; }
        public string InEmployeeSign { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LeaveFromDate { get; set; }
        public string LeaveToDate { get; set; }
        public string ShiftName { get; set; }
    }
}
