//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Round
    {
        public int Id { get; set; }
        public string MrNo { get; set; }
        public string IpNo { get; set; }
        public string NameOfPatient { get; set; }
        public string DrName { get; set; }
        public string Remarks { get; set; }
        public string ActionTaken { get; set; }
        public string AttenderSign { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
