//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Occurance
    {
        public int OccuranceId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> DateOfRegister { get; set; }
        public string Occurance { get; set; }
        public string Shift { get; set; }
        public string OccuranceTime { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeSign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
