//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Demo
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string ProductDetails { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string DcNo { get; set; }
        public string HandoverToSecurity { get; set; }
        public string HandoverToSecuritySign { get; set; }
        public string HandOverToDepartment { get; set; }
        public string HandOverToPersonName { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public string HandOverRemarks { get; set; }
        public string ReturnSecurity { get; set; }
        public string ReturnSecuritySign { get; set; }
        public string ReturnDepartment { get; set; }
        public string ReturnPersonName { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnRemarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
