//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_LifeCell
    {
        public int Id { get; set; }
        public string PatientMRNo { get; set; }
        public string NameOfPatient { get; set; }
        public string RoomNo { get; set; }
        public string CompanyName { get; set; }
        public string PatientContactNumber { get; set; }
        public string ParamedicName { get; set; }
        public string ContactNumber { get; set; }
        public string Security { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string InSign { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public string OutSign { get; set; }
        public string InRemarks { get; set; }
        public string OutRemarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
