//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_InWardReturnable
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Department { get; set; }
        public string GatePassNo { get; set; }
        public string SupplierName { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string AuthorizeBy { get; set; }
        public string Reason { get; set; }
        public string Security { get; set; }
        public string SecuritySign { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutTime { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ExceptedDate { get; set; }
        public string InSecurity { get; set; }
        public string InSecuritySign { get; set; }
        public string InPerson { get; set; }
        public string InPersonSign { get; set; }
    }
}
