//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_PatientTransfer
    {
        public int Id { get; set; }
        public string PatientMRNo { get; set; }
        public string NameOfPatient { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<System.DateTime> OutDateTime { get; set; }
        public string OutRemarks { get; set; }
        public string NurseIncharge { get; set; }
        public string NurseInchargeSign { get; set; }
        public string Security { get; set; }
        public string SecuritySign { get; set; }
        public string SecuritySupervisor { get; set; }
        public string SecuritySupervisorSign { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string InRemarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string InLocation { get; set; }
    }
}
