//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_VehicleParking
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string ParkingLocation { get; set; }
        public string WheelerType { get; set; }
        public Nullable<System.DateTime> DateOfRegister { get; set; }
        public string VehicleNameOrNumber { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public string InDriver { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string OutDriver { get; set; }
        public string Purpose { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string InSecurity { get; set; }
        public string InSecuritySign { get; set; }
        public string InDriverSign { get; set; }
        public string OutSecurity { get; set; }
        public string OutSecuritySign { get; set; }
        public string OutDriverSign { get; set; }
    }
}
