//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Key
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string KeyDepartment { get; set; }
        public string KeyNumber { get; set; }
        public Nullable<int> NoOfKeys { get; set; }
        public string KeyIssuerName { get; set; }
        public Nullable<System.DateTime> TakingDateTime { get; set; }
        public string TakingSignature { get; set; }
        public string ReturnSignature { get; set; }
        public Nullable<System.DateTime> ReturnDateTime { get; set; }
        public string TakingRemarks { get; set; }
        public string ReturnRemarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string TakingSecuritySignature { get; set; }
        public string TakingSecurity { get; set; }
        public string ReturnSecurity { get; set; }
        public string ReturnSecuritySign { get; set; }
        public Nullable<int> ReturnEmployee { get; set; }
    }
}
