//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lms_CourseQuiz
    {
        public int QuizId { get; set; }
        public string QuizName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
