//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_InwardNonReturnable
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string SupplierName { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Amount { get; set; }
        public string InvoiceNo { get; set; }
        public string HandOverTo { get; set; }
        public string HandOverToSign { get; set; }
        public string Security { get; set; }
        public string SecuritySign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
