//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Daak
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<System.DateTime> DateOfRegister { get; set; }
        public string Description { get; set; }
        public string PODNo { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string Driver { get; set; }
        public string DriverSign { get; set; }
        public string CourierName { get; set; }
        public string HandOverto { get; set; }
        public string HandOverSign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
