//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_Fuel
    {
        public int Id { get; set; }
        public string VechicleNumber { get; set; }
        public string OpeningKM { get; set; }
        public string ClosingKM { get; set; }
        public string TotalKM { get; set; }
        public string BillNo { get; set; }
        public string FuelFilled { get; set; }
        public string Amount { get; set; }
        public string DriverName { get; set; }
        public string SecuritySupervisor { get; set; }
        public string SecuritySupervisorSign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string FuelQty { get; set; }
    }
}
