//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_BioMedicalWaste
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string SlipNo { get; set; }
        public string NameOfHCE { get; set; }
        public string MedicareRegistratioNo { get; set; }
        public Nullable<System.DateTime> DateOfRegister { get; set; }
        public Nullable<int> YellowNoOfBags { get; set; }
        public string YellowWeightKgs { get; set; }
        public Nullable<int> BlueNoOfBags { get; set; }
        public string BlueWeightKgs { get; set; }
        public Nullable<int> RedNoOfBags { get; set; }
        public string RedWeightKgs { get; set; }
        public Nullable<int> SharpsNoOfBags { get; set; }
        public string SharpsWeightKgs { get; set; }
        public string TakenBy { get; set; }
        public string TakenBySign { get; set; }
        public string Security { get; set; }
        public string SecuritySign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
