//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_LostFound
    {
        public int Id { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Items { get; set; }
        public string LostIsEmployeeOrOther { get; set; }
        public string Lost_or_HandOverPerson { get; set; }
        public string LostRegisterSecurity { get; set; }
        public string LostRegisterSecuritySign { get; set; }
        public string LostRemarks { get; set; }
        public Nullable<System.DateTime> LostDate { get; set; }
        public string LostApproximateTime { get; set; }
        public string FoundIsEmployeeOrOther { get; set; }
        public string FoundPerson { get; set; }
        public string FoundRegisterSecurity { get; set; }
        public string FoundRegisterSecuritySign { get; set; }
        public string FoundRemarks { get; set; }
        public Nullable<System.DateTime> FoundDate { get; set; }
        public string FoundApproximateTime { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Handoverto { get; set; }
        public string HandovertoSign { get; set; }
        public string LostPersonAddress { get; set; }
        public string FoundPersonAddress { get; set; }
        public string HandoverPersonAddress { get; set; }
    }
}
