//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_MobileDepositing
    {
        public int Id { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string TokenNumber { get; set; }
        public string SecurityInSign { get; set; }
        public string EmployeeInSign { get; set; }
        public string SecurityOutSign { get; set; }
        public string EmployeeOutSign { get; set; }
        public string InSecurity { get; set; }
        public string OutSecurity { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
