//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHsApp.DataModelRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register_PatientDischarge
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string PatientMRNo { get; set; }
        public string NameOfPatient { get; set; }
        public string Passes { get; set; }
        public string RoomNo { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutTime { get; set; }
        public string IpExecutive { get; set; }
        public string IpExecutiveSign { get; set; }
        public string Security { get; set; }
        public string SecuritySign { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
